PX4/NuttX branch test: master
NuttX:
 - https://github.com/PX4-NuttX/nuttx/tree/master
 - https://github.com/PX4-NuttX/nuttx/commit/352e5a4b5e418948c0aba10efa68f1df16ba3f2e

Changes from PX4/NuttX (https://github.com/PX4/NuttX/commit/fdf1837077104e80912a2c46ff159fdacc8b06f9) in current PX4/master (9a96ca14be2ea18ad232861aa4491176157bb114)
https://github.com/PX4/NuttX/compare/fdf1837077104e80912a2c46ff159fdacc8b06f9...352e5a4b5e418948c0aba10efa68f1df16ba3f2e

352e5a4b5e (HEAD, origin/master) tiva/lm3s6965-ek: Fix a build error with certain configurations
f79b47ad25 tiva_serial.c: Make this buildable with certain configurations
3df686e10f sim: berr() unknown relocation type
3ead7795b2 sim: Add loadable module definitions
7f1f930a7b Remove unneeded dependency on USB
1200c6d429 Using debug macros for memory card
1832172432 Fix wrong name for CONFIG_MMCSD_SPI
0b25b96759 net/netlink/netlink_route.c:  Fix a typo.
46ad645efc mm: Add a bunch of assertions
c1a32fb9dd compiler.h: clang actually has long long

Apps:
 - https://github.com/PX4/NuttX-apps/tree/master
 - https://github.com/PX4/NuttX-apps/commit/afa51c2e0076b796d3daa79b86d91d5f2327a1ce

Changes from PX4/NuttX-apps (https://github.com/PX4/NuttX-apps/commit/91b6ad6a0d00ac107088b18588cd54d40e3cb796) in current PX4/master (9a96ca14be2ea18ad232861aa4491176157bb114)
https://github.com/PX4/NuttX-apps/compare/91b6ad6a0d00ac107088b18588cd54d40e3cb796...afa51c2e0076b796d3daa79b86d91d5f2327a1ce

afa51c2e (HEAD -> master, origin/master) Fix documentation typos
de4d52d4 wireless: gs2200m: Add support for setsockopt_request()
c5673957 Remove unused BUILTIN_PROXY_STACKSIZE config
44b8c9c5 apps/examples/tcpblaster:  Fix compile errors in loopback mode.
539d0854 examples: elf: Fix warnings when compiled for RISC-V 64bit
779197c6 Ensure all source code end with one and only one newline
4a13a089 testing/smp: Replace up_cpu_index with sched_getcpu
d2e1c8a4 apps/wireless/gs2200m/gs2200m_main.c:  Eliminate a warning
c8dbd59e netutils/telnetd/telnetd_daemon.c: Avoid a warning if CONFIG_NET_SOCKOPTS=n
d2522e28 apps/netutils/telnetd:  Fix undefined reference to setsockopt.